name = "danibednarskicom"
account_id = "6daf0f5cbb5a23380c83e9bed1e7e1a9"
route = "danibednarski.com/*"
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-09-19"
main = "workers-site/index.js"

[site]
bucket = "./build"

[build]
command = "npm run build && sed -i '' 's/browserTTL: null/browserTTL: 31536000/g' workers-site/index.js"
