name: Node.js CI - danibednarski.com

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/danibednarski.com/repo

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Clean Install
      run: npm ci

    - name: Build
      run: npm run build --if-present
